import { europaGrotesk } from "@/components/CoverVideo";
import "./globals.css";
import { Sirin_Stencil } from "next/font/google";

export const sirinStencil = Sirin_Stencil({
  subsets: ["latin"],
  weight: "400",
});
// export const metadata = {
//   title: "Chicity-Fashion Brand",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Valentina López Arango Consultora</title>
      <meta
  name="description"
  content="Descubre el poder de la previsión estratégica con Valentina Consultora. Explora nuestro sitio web animado con desplazamiento fluido de Lenis y textos dinámicos impulsados por Framer Motion. Vive una experiencia inmersiva con efectos de parallax y animaciones de scroll creadas con GSAP. Diseñado con excelencia en Tailwind CSS y optimizado para el máximo rendimiento con SSR en NextJS. Más que un sitio web: una experiencia donde la estrategia y la innovación se encuentran."
/>

      </head>
      <body className={europaGrotesk.className}>{children}</body>
    </html>
  );
}
